### ISSUE TITLE
Travis CI failing

### ISSUE THREAD

**Issue by msabramo** [zopefoundation/zopetoolkit#1]
With

~~~
WARNING: intersphinx inventory 'http://docs.zope.org/zope.structuredtext/objects.inv' not fetchable due to <class 'urllib2.HTTPError'>: HTTP Error 403: Forbidden
While:
  Installing ztk-docs.
~~~

**Comment by tseaver** [comment]
Ugh.

- [Disabled the intersphinx mapping stuff](8da36)
- [Fixed the `generate-releases` step to straddle Python2-Python3](49460).
- [Made the update script Python 2.6 compatible](ba2dab5).

Travis is [now happy](https://travis-ci.org/zopefoundation/zopetoolkit/builds/48653973).
