### ISSUE TITLE
Use buildout inside tox and Travis-CI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zopetoolkit#16]
The ZTK packages currently have up to three ways to run their tests:

* Install via `zc.buildout` for a specific Python version + run via `bin/test`
* Install and run via `tox` for all supported Python versions
* Install for a specific Python version in Travis-CI + run tests via `bin/test` or even via `python setup.py test`.

The Zope 4 packages are now using a n interesting template which uses buildout for tox and Travis-CI, too. For example see [five.localsitemanager](https://github.com/zopefoundation/five.localsitemanager/commit/038d77ebe733ea77c99bcfebfdb06fc22adbbba5).

This template could be adapted in ZTK, but coverage report should be added, too.

Packages to update: 

- [ ] zope.annotation
- [ ] zope.applicationcontrol
- [ ] zope.authentication
- [ ] zope.browser
- [ ] zope.browsermenu
- [ ] zope.browserpage
- [ ] zope.browserresource
- [ ] zope.cachedescriptors
- [ ] zope.catalog
- [ ] zope.component
- [ ] zope.componentvocabulary
- [ ] zope.configuration
- [ ] zope.container
- [ ] zope.contentprovider
- [ ] zope.contenttype
- [ ] zope.copy
- [ ] zope.copypastemove
- [ ] zope.datetime
- [ ] zope.deferredimport
- [ ] zope.deprecation
- [ ] zope.dottedname
- [ ] zope.dublincore
- [ ] zope.error
- [ ] zope.event
- [ ] zope.exceptions
- [ ] zope.filerepresentation
- [ ] zope.formlib
- [ ] zope.hookable
- [ ] zope.i18n
- [ ] zope.i18nmessageid
- [ ] zope.index
- [ ] zope.interface
- [ ] zope.intid
- [ ] zope.keyreference
- [ ] zope.lifecycleevent
- [ ] zope.location
- [ ] zope.login
- [ ] zope.mimetype
- [ ] zope.minmax
- [ ] zope.pagetemplate
- [ ] zope.password
- [ ] zope.pluggableauth
- [ ] zope.principalannotation
- [ ] zope.principalregistry
- [ ] zope.processlifetime
- [ ] zope.proxy
- [ ] zope.ptresource
- [ ] zope.publisher
- [ ] zope.ramcache
- [ ] zope.schema
- [ ] zope.security
- [ ] zope.securitypolicy
- [ ] zope.sendmail
- [ ] zope.session
- [ ] zope.site
- [ ] zope.size
- [ ] zope.structuredtext
- [ ] zope.tal
- [ ] zope.tales
- [ ] zope.testing
- [ ] zope.testrunner
- [ ] zope.traversing
- [ ] zope.viewlet

**Comment by jamadden** [comment]
If you're suggesting that each of those packages should be changed so that Travis and local tox runs use buildout, I'm a strong -1.

- It doesn't match the common virtualenv-based development environment. 
- It adds a dependency and another configuration file to maintain
- Caching on travis is slightly more complicated.
- It's typically slower than a pure pip based solution.
- Coverage reports are more complicated (compare ZODB's [.travis.yml](https://github.com/zopefoundation/ZODB/blob/master/.travis.yml) with, say, [zope.file's](https://github.com/zopefoundation/zope.file/blob/master/.travis.yml)

buildout is a great tool for *system*  construction and integration, but I don't see many benefits for developing one single package.

**Comment by hannosch** [comment]
I'm +0.

I think standardization is good, but the reasons why we choose zc.buildout for Zope 4 packages are different enough, so they don't directly apply to the Zope toolkit.

One of the main reasons we use buildout for the Zope 4 packages, is the need to have a stable version definition list (or KGS / known good set of versions). On master / development branches we extend from https://github.com/zopefoundation/Zope/blob/master/versions.cfg and on maintenance branches for the older Zope 2.13 release line, we extend from https://github.com/zopefoundation/Zope/blob/2.13/version_ranges.cfg.

Most of the Zope 4 packages have a non-trivial list of dependencies, and generally don't work with the latest release of everything. Maintenance branches shouldn't work with the latest releases, but some clearly defined set of older releases. Exceptions to this are some of the low-level projects like ExtensionClass and Acquisition, but even Persistence needs specific versions of persistent.

On the Zope toolkit level, these version dependencies are generally not that much of a problem. And we track them differently via the extra / optional https://github.com/zopefoundation/zopetoolkit/ repo.

For testrunners, I think standardizing on zope.testrunner and avoiding the `python setup.py test` indirection makes sense. There also seems to be no good reason anymore to use nose, where zope.testing layers don't prevent it in the first place. If we wanted to adopt a test runner, which has a major mindshare in the broader Python community, we'd have to switch to py.test these days. But again zope.testing layers prevent that for most projects.

**Comment by icemac** [comment]
You are right ZTK is different from Zope 2 so it does not make much sense to use buildout in tox. So see #17 as my alternative proposal.
