### ISSUE TITLE
build for Python 3.8 is broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zopetoolkit#35]
https://travis-ci.org/zopefoundation/zopetoolkit/jobs/525832370

**Comment by mgedmin** [comment]
The following packages have failures:

- [ ] zope.i18nmessageid
- [ ] zope.security
- [ ] zope.hookable
- [ ] zope.password
- [ ] zope.index

**Comment by mgedmin** [comment]
The zope.password failure is weird, and I cannot reproduce it locally with `tox -e py38`.

**Comment by mgedmin** [comment]
I cannot reproduce the zope.hookable failure with `tox -e py38` either.

**Comment by mgedmin** [comment]
Surprise: I cannot reproduce the zope.security failure with `tox -e py38` either.

**Comment by mgedmin** [comment]
Same story with zope.index and `tox -e py38`.  There's one interesting deprecation warning:

> /home/mg/src/zopefoundation/zope.index/.tox/py38/lib/python3.8/site-packages/zope/index/text/okapiindex.py:347: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using `__int__` is deprecated, and may be removed in a future version of Python.

**Comment by mgedmin** [comment]
Same story with zope.i18nmessageid and `tox -e py38`: no failures on my machine.

I suppose Travis is using a more recent 3.8 nightly build?

**Comment by mgedmin** [comment]
Nope: current CPython git master + `tox -re py38` passes all the tests for zope.hookable, zope.password and zope.i18nmessageid.

**Comment by mgedmin** [comment]
Oh, wait, zopetoolkit tests released versions and not git masters, so maybe we had actual failures that got fixed but not released?

**Comment by mgedmin** [comment]
I'm unable to run `bin/buildout` on 3.8 because `lxml`'s build fails (error: too few arguments to function ‘PyCode_New’).  I get the same error with `python3.8 -m pip install lxml`.

**Comment by mgedmin** [comment]
Cython issue filed: https://github.com/cython/cython/issues/2938

**Comment by icemac** [comment]
Python 3.8 is currently green in TravisCI! 🎆

**Comment by icemac** [comment]
Thank you all for fixing it.
