### ISSUE TITLE
tox is broken: couldn't open ...buildout.cfg

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zopetoolkit#52]
Currently I am running tox for all Zope and Plone repos, as the upcoming tox4 release is a complete rewrite and some breaking changes and regressions are expected, see https://github.com/zopefoundation/meta/issues/66

While I noticed an endless setuptools upgrade loop for tox4, tox (3) is broken anyway.

```
❯ tox -e py38
py38 installed: zc.buildout==2.13.3
py38 run-test-pre: PYTHONHASHSEED='3646606669'
py38 run-test: commands[0] | /home/jugmac00/All/output_zope/zopefoundation/zopetoolkit/.tox/py38/bin/buildout -c /home/jugmac00/All/output_zope/zopefoundation/zopetoolkit/buildout.cfg buildout:directory=/home/jugmac00/All/output_zope/zopefoundation/zopetoolkit/.tox/py38 install test-ztk
Upgraded:
  setuptools version 50.3.0;
restarting.
While:
  Initializing.
Error: Couldn't open /home/jugmac00/All/output_zope/zopefoundation/zopetoolkit/.tox/py38/buildout.cfg
ERROR: InvocationError for command /home/jugmac00/All/output_zope/zopefoundation/zopetoolkit/.tox/py38/bin/buildout -c buildout.cfg buildout:directory=/home/jugmac00/All/output_zope/zopefoundation/zopetoolkit/.tox/py38 install test-ztk (exited with code 1)
_____________________________________________________________________________ summary _____________________________________________________________________________
ERROR:   py38: commands failed
```

There is still a "test passing" badge from Travis in the readme, although Travis does not work anymore.

The GHA tests are not executed regularly - maybe a weekly run would be good so breakages are spotted early on.

**Comment by mauritsvanrees** [comment]
Looks like this is the same failure that I saw when working on a `plone.api` PR. I [pinned](https://github.com/plone/plone.api/pull/453/commits/e990c5d6cf11e2732b833d575f2cc25e037e6b5f) zc.buildout and setuptools to prevent an upgrade. Otherwise `bin/buildout other/dir/buildout.cfg` would start out okay, but then upgrade and restart itself, and complain that `buildout.cfg` cannot be found in the current directory. I guess this is a bug in the self-upgrade code of buildout.

**Comment by jugmac00** [comment]
I had the exact same error in https://github.com/plone/plone.memoize/issues/24

I did not try to investigate what's broken for `plone.api` (on tox4) as there was already an issue https://github.com/plone/plone.api/issues/448

**Comment by icemac** [comment]
Fixed somewhere along the way.
